main: de.Lathanael.SimpleCalc.SimpleCalc
name: SimpleCalc
description: Simple calculator for Bukkit
author: Lathanael
version: ${project.version} (BUILD ${git.build.time})
softdepend: [Spout]

commands:
    simple_calc:
        description: Used to initiate a calculation
        aliases: [calc, scalc]
        usage: |
            /<command> <exp> - To calculate an expression simply type /<command> [expression], e.g. /<command> 5+3
            /<command> - Opens this usage information or if Spout is installed a Calculator Window